### PR TITLE
Fixin quirks 

### LINKED ISSUE #13: Hitting `enter` for first selection
To reproduce:

- Begin typing a search, like `100 mark` (for `100 market street`)
- Wait for suggestions but don't hit up or down
- Hit enter (nothing will happen)

I think ideally if you have no suggestions selected and you hit enter in the text field we select the first item and trigger the selection.

### PR DESCRIPTION
**Pull request by heyitsgarrett**
This commit fixes #13 + #14:

- Handles `enter` key press in cases where no result is highlighted
- Adds an optional loading property to the Geocoder. This attaches a `.loading` class to the results list `ul` and leaves it to the user to decide what to do with it. I played with an additional div or attaching it to the input class, but this allows for the most flexibility.
- Newest versions of React also don't require the line `/** @jsx React.DOM */` declaration, so I've removed that from the example code.

@yhahn -- would love your eyes on this before merge.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -89,6 +94,9 @@ var Geocoder = React.createClass({
         break;
       // accept
       case 13:
+        if( this.state.results.length > 0 ) {
+          this.clickOption(this.state.results[0]);
```
Comment (yhahn) [inline index.js]: Should this set focus on `0` as well? Seeing `enter` trigger using the result but leaving the first option unhighlighted.

**Comment by heyitsgarrett** [comment]
Few more tweaks:

- set focus on `enter` keypress
- set focus when clicking result
- keep focus on input when clicking result
